//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIUIFYPPortall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentation
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ProposalPath { get; set; }
        public string Status { get; set; }
        public Nullable<bool> View { get; set; }
        public string GroupId { get; set; }
        public string PanelId { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
