//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIUIFYPPortall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalExternal
    {
        public int Id { get; set; }
        public string Marks { get; set; }
        public string GroupId { get; set; }
        public string PanelId { get; set; }
        public string Remarks { get; set; }
        public string QA { get; set; }
        public string Documentation { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
