//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIUIFYPPortall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel
    {
        public int Id { get; set; }
        public string Teacher1 { get; set; }
        public string Teacher2 { get; set; }
        public string Teacher3 { get; set; }
        public string GroupId1 { get; set; }
        public string GroupId2 { get; set; }
        public string GroupId3 { get; set; }
        public string GroupId4 { get; set; }
        public string GroupId5 { get; set; }
        public string GroupId6 { get; set; }
        public string GroupId7 { get; set; }
        public string GroupId8 { get; set; }
        public string GroupId9 { get; set; }
        public string GroupId10 { get; set; }
    }
}
